<?php
	
function fivestar_average_form(){

		global $user;
		if($user->uid==""){
			drupal_add_css("sites/all/modules/fivestar/css/fivestar.css");
			drupal_add_css("/sites/default/files/fivestar/basic/basic.css");
		}

		$field = array();
		$field_name = array();
		$avg_values = array();
		$node_id = split('/',$_GET['q']);
		$nid=$node_id['1'];
		$que= "SELECT * from {category}";
		$cname = db_query($que);
		while($item = db_fetch_array($cname)){
			
			array_push($field_name,$item['category']);
						
			$cid = db_query("SELECT cid  from {comments}  where nid='".$nid."'");
			$comment_id = "(";	
			while($c_id = db_fetch_array($cid)){
				$comment_id .=$c_id['cid'].",";
				 
			}	
			$comment_id .= (sizeof($comment_id))-1;
			$comment_id .=")";
			$query="select avg(value) as aver from {voting_comment} where category_id=
			".$item['category_id']." and cid in ".$comment_id;
			$value = db_query($query);
			$avg = db_fetch_array($value);
			array_push($avg_values,round($avg['aver']));
			$comment_id="";
			
		}
		
	   
		for($i=0;$i<sizeof($field_name);$i++){
			if($avg_values[$i] >= '20'){
				$a='on';
				$b=$c=$d=$e='off';
			}
			if($avg_values[$i] >= '40'){
				$a=$b='on';
				$c=$d=$e='off';
			}
			if($avg_values[$i] >= '60'){
				$a=$b=$c='on';
				$d=$e='off';
			}	
			if($avg_values[$i] >= '80'){
				$b=$c=$a=$d='on';
				$e='off';
			}
			if($avg_values[$i] == '100'){
				$b=$c=$d=$a=$e='on';
			}
		
			echo '<div id="newdiv" style="position:relative;width:450px;left:200px;">
			      <div class="field field-type-fivestar field-'.$field[$i].'">
		  	      <div class="field-label" style="font-weight:bold;position:relative;right:-250px;bottom:0px;width:130px;border:0px solid green;">'.$field_name[$i].':&nbsp;</div>
		 	      <div class="field-items">
     			      <div class="field-item even">
	                      <div class="fivestar-widget-static fivestar-widget-static-5 clear-block" >
			      <div class="star star-1 star-odd star-first"><span class="'.$a.'">2</span></div>
			      <div class="star star-2 star-even"><span class="'.$b.'"></span></div>
			      <div class="star star-3 star-odd"><span class="'.$c.'"></span></div>
			      <div class="star star-4 star-even"><span class="'.$d.'"></span></div>
			      <div class="star star-5 star-odd star-last"><span class="'.$e.'"></span></div>
			      </div></div>
			      </div></div></div>';

		}

	
		
}
